export const SHOW_CATEGORIES = 'SHOW_CATEGORIES';
export const SHOW_RECIPES = 'SHOW_RECIPES';
export const LOADING_RECIPES = 'LOADING_RECIPES';
export const SHOW_FAVORITES = 'SHOW_FAVORITES';
export const LOADING_FAVORITES = 'LOADING_FAVORITES';
export const TOGGLE_FAVORITES = 'TOGGLE_FAVORITES';
export const SHOW_POSTS = 'SHOW_POSTS';
export const LOADING_POSTS = 'LOADING_POSTS';
